### ISSUE TITLE
Image processing on linux is not working

### ISSUE THREAD

**Issue by maraf** [neptuo/Recollections#50]
```
An unhandled exception was thrown by the application.
System.TypeInitializationException: The type initializer for 'Gdip' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
   at Interop.Libdl.dlopen(String fileName, Int32 flag)
   at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipLoadImageFromFile(String filename, IntPtr& image)
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at Neptuo.Recollections.Entries.Services.ImageResizeService.Thumbnail(String inputPath, String outputPath, Int32 width, Int32 height) in /src/src/Recollections.Api/Entries/Services/ImageResizeService.cs:line 17
   at Neptuo.Recollections.Entries.Services.ImageService.ComputeOtherSizesAsync(Entry entry, Image image) in /src/src/Recollections.Api/Entries/Services/ImageService.cs:line 72
   at Neptuo.Recollections.Entries.Services.ImageService.CreateAsync(Entry entry, IFormFile file) in /src/src/Recollections.Api/Entries/Services/ImageService.cs:line 61
   at Neptuo.Recollections.Entries.Controllers.ImageController.<>c__DisplayClass12_0.<b__0>d.MoveNext() in /src/src/Recollections.Api/Entries/Controllers/ImageController.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
   at Neptuo.Recollections.Entries.Controllers.ImageController.RunEntryAsync(String entryId, Func`2 handler) in /src/src/Recollections.Api/Entries/Controllers/ImageController.cs:line 53
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
```

**Comment by maraf** [comment]
dotnet/corefx#31895

**Comment by maraf** [comment]
Include these in docker image:
```
RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y libgdiplus
RUN ln -s /usr/lib/libgdiplus.so /usr/lib/gdiplus.dll
```
